name: Demo Workflow
on:
  workflow_dispatch:
    inputs:
      failure_type:
        description: 'Type of failure to simulate'
        required: true
        default: 'dependency'
        type: choice
        options:
        - dependency
        - cpu
        - memory
        - network

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run demo with failure
        env:
          FAILURE_TYPE: ${{ github.event.inputs.failure_type }}
        run: python app.py
      
      - name: Send webhook to SRE Agent
        if: failure()
        run: |
          curl -X POST http://your-local-ip:8080/webhooks/github \
            -H "Authorization: Bearer your-api-key" \
            -H "Content-Type: application/json" \
            -d '{
              "repository": "${{ github.repository }}",
              "workflow": "${{ github.workflow }}",
              "run_id": "${{ github.run_id }}",
              "failure_type": "${{ github.event.inputs.failure_type }}",
              "error": "Workflow failed with ${{ github.event.inputs.failure_type }} error"
            }'